// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXOkszxVjAbCIr0yfTYpDSbgvO0Mm4oZo',
    appId: '1:413337624369:web:d92d46052dc17ee2561a10',
    messagingSenderId: '413337624369',
    projectId: 'chat-app-39fcd',
    authDomain: 'chat-app-39fcd.firebaseapp.com',
    storageBucket: 'chat-app-39fcd.appspot.com',
    measurementId: 'G-P448HNJN9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZkF6jMSRF5FXcGeW2hKmoSDgVIM9G6z8',
    appId: '1:413337624369:android:21308a9dfa701c1a561a10',
    messagingSenderId: '413337624369',
    projectId: 'chat-app-39fcd',
    storageBucket: 'chat-app-39fcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGpT3KQlJfYFPn9eWnJOxN9l0X1vzbB0Q',
    appId: '1:413337624369:ios:23c4f932322dbb3b561a10',
    messagingSenderId: '413337624369',
    projectId: 'chat-app-39fcd',
    storageBucket: 'chat-app-39fcd.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGpT3KQlJfYFPn9eWnJOxN9l0X1vzbB0Q',
    appId: '1:413337624369:ios:23c4f932322dbb3b561a10',
    messagingSenderId: '413337624369',
    projectId: 'chat-app-39fcd',
    storageBucket: 'chat-app-39fcd.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
